name: StaffListUI-master
author: SigitGamersY
version: 1.0.0 
api: [3.0.0, 4.0.0]
main: StaffListUi\Main

commands:
  staff:
    usage: /staff
    aliases: [sui]
    description: "ยงoยง6See StaffList in your Server"
